### ISSUE TITLE
How to import Mp3 files resp. open existing files

### ISSUE THREAD

**Issue by hitam4450** [libasys/audios#10]
Hi,

I could not find an import / open dialog/ button to make my huge collection of MP3 files available for playing in audios!  How to do that??
regards, hitam4450

**Comment by andreibranescu** [comment]
The import is not done by the application itself. Just copy your music files in the Music folder of your OwnCloud and then push the refresh library icon (round arrows) in the Audios application. There's no progress bar, so the scanning of your files could take a while if you have a big library. If you have thousands of files, give it at least a few minutes.

**Comment by hitam4450** [comment]
HI,

I do not see round arrows in the interface. The app is user unfriendly and not intuitive to normal users! 
Will uninstall only! Waste of time and effort!
regards, hitam4450

**Comment by hitam4450** [comment]
I clicked on a mp3 file, it starts playing but nothing can be seen in audios....it is just like ghost playing!

I am going to uninstall all + apps from Sebastian, they look nice but they are not intuitive at all! 

i am going to revert to the base apps, much better an easier to use!
regards, hitam4450

**Comment by libasys** [comment]
Do it, the user have the choice, what app he wants to install! And if a app isn't much userfriendly then create a pull request with your missing improvements! 
Thanks

**Comment by hitam4450** [comment]
App is not even experimental in this stage. Maybe pre-alpha !

Not usable & uninstalled!

regards, hitam4450
