### ISSUE TITLE
Can't reset 

### ISSUE THREAD

**Issue by dtb1987** [libasys/audios#11]
I can't reset the app, i want to reset it then rescan my collection because now when ever i try to click on an album none of the songs show up

**Comment by libasys** [comment]
Hi @dtb1987 thanks for your report. Can you please add some more information about your enviroment (webserver, database, etc)! Are there some error logs?

Thanks!

**Comment by dtb1987** [comment]
I managed to fix it, What i had to do is go into the database and manually delete all entries related to audios.

my server is:

Debian Linux 8.0

4 Core 1GHz processor 

MySQL database

Apache2 webserver

PHP 5.6.9

Owncloud 8.1.1

Also i had to flush my logs while i was trying to figure out what exactly i needed to delete from my database (sorry i really should have saved a copy to send in but i guess i didn't think about it)

But basically after i cleared out my database and reinstalled the app everything was fine.

**Comment by libasys** [comment]
Ok thanks for the feedback, but i think i write a function to clear the music database of a user! Thanks for the hint!

**Comment by dtb1987** [comment]
No problem thanks for getting back to me

**Comment by libasys** [comment]
New version is available on master (Vers. 1.2.4) added resetting function and editing ID3 Infos of a mp3 file! And some bugfixes!

**Comment by dtb1987** [comment]
thanks i'll check it out

**Comment by dtb1987** [comment]
so how does the reset function work?

**Comment by libasys** [comment]
on the left sidebar is now a delete button trashbox! if you click on this then all entries of your music library (of an user) in the database will be deleted! And then you can do a new scan for music and the music library will be filled again!

**Comment by dtb1987** [comment]
Nice!
