### ISSUE TITLE
When I click a song, sometime the file open in my browser

### ISSUE THREAD

**Issue by Antopower** [libasys/audios#17]
Hi, I just installed your app and I like it! But I'm having a bug when I want to start a song. If I click on the title of the song, everything is fine. But if i click on the number or the time, my browser will go to the link of the song and play instead of staying in the MP3 Player.

I tried in your demo site and the issue is there also.

If i click this for example:  
![sans titre](https://cloud.githubusercontent.com/assets/3418546/9697783/e88cd638-5369-11e5-9ab6-2d9c0315afce.jpg)  

This will happen:  
![sans titre](https://cloud.githubusercontent.com/assets/3418546/9697786/07488054-536a-11e5-9d23-f7fa0267814d.png)  

I'm using version 1.2.4 of your player and Owncloud 8.1.
This also happen in the album view and the playlist view.  

Thanks for your time, If you need more info, please ask :)

**Comment by libasys** [comment]
thanks for your bug report! i will investigate! confirmed!
