### ISSUE TITLE
App breaking the owncloud trash icon

### ISSUE THREAD

**Issue by Antopower** [libasys/audios#18]
Hi, after updating to 1.2.5, i realised that the trash on the owncloud files app was broken. After looking around a bit in the code, i found the issue. You are changing CSS class that owncloud use.

It create this odd trashbin:
![23b215a36d84df4ef3e3b0348c0fd43d](https://cloud.githubusercontent.com/assets/3418546/9700065/ccef32d0-53c4-11e5-9f28-ec64750fdefe.png)

This is the normal trashbin:
![1bc6d7e725677a78bc4e83c8e246201a](https://cloud.githubusercontent.com/assets/3418546/9700040/fe7aa4f2-53c3-11e5-9d66-2b2c0bd432f2.png)

To fix this issue, i simply deleted the line 937 and 938 in the style.css file. So if you could fix this in later version, it could be great! :)

**Comment by libasys** [comment]
thanks for your bug report fixed with next commit on master

**Comment by libasys** [comment]
fixed
