### ISSUE TITLE
oc 8.2.2

### ISSUE THREAD

**Issue by szepeviktor** [libasys/audios#27]
@libasys Will audios support oc 8.2.2?

**Comment by smartroad** [comment]
I am using it on 8.2.2 right now (listening to it play as I type this).

**Comment by Rello** [comment]
as this git does not seem to be maintained, I can offer the continuation at
https://github.com/z000ao8q/audios2

This issue is solved there; including support for more audio formats;
feel free to support me

**Comment by szepeviktor** [comment]
Thank you.
