### ISSUE TITLE
Cannot play mp3 from mp3 app

### ISSUE THREAD

**Issue by apg1980** [libasys/audios#4]
Hello,
i've activated successfully the app in my oc 8.1 instance.
I can play mp3 from files app (start/stop).
But within the mp3 app i get some mp3 covers but are unable to play songs.
This is from my oc log:

Fatal   index   Exception: {"Exception":"Doctrine\DBAL\Exception\NotNullConstraintViolationException","Message":"An exception occurred while executing 'INSERT INTO `oc_audios_tracks` (`user_id`,`title`,`number`,`artist_id`,`album_id`,`length`,`file_id`,`bitrate`,`mimetype`) VALUES(?,?,?,?,?,?,?,?,?)' with params [\"08598A5C-6FB6-450C-A152-628B33F56156\", \"Marteria - Marteria Girl .mp3\", 0, 1, 1, null, 295135, 0, \"audio\\/mpeg\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'length' cannot be null","Code":0,"Trace":"#0 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))\n#1 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/db\/statementwrapper.php(73): Doctrine\DBAL\Statement->execute(Array)\n#3 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/audios\/controller\/scannercontroller.php(390): OC_DB_StatementWrapper->execute(Array)\n#4 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/audios\/controller\/scannercontroller.php(283): OCA\Audios\Controller\ScannerController->writeTrackToDB(Array)\n#5 [internal function]: OCA\Audios\Controller\ScannerController->scanForAudios()\n#6 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Audios\Controller\ScannerController), 'scanForAudios')\n#8 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/app.php(108): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Audios\Controller\ScannerController), 'scanForAudios')\n#9 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\AppFramework\App::main('ScannerControll...', 'scanForAudios', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#10 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\n#11 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\n#12 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/base.php(867): OC\Route\Router->match('\/apps\/audios\/sc...')\n#13 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/index.php(40): OC::handleRequest()\n#14 {main}","File":"\/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":112}

**Comment by libasys** [comment]
Hi @apg1980 thanks for your bug report, please add some more information about your enviroment (webserver, database, etc) Thanks!
