### ISSUE TITLE
Shared audio requires login

### ISSUE THREAD

**Issue by szepeviktor** [libasys/audios#7]
Good morning @libasys !

A shared MP3 file: https://*.net/index.php/apps/audios/getpublicaudiostream2012-12-08%2012-58-19%20IPOP%20computer%20record.mp3?token=2UIc2evTz6GQana
requires login.
Please advise.

Latest audios, `$OC_Version = array(8,1,0,8);`

**Comment by szepeviktor** [comment]
When logged in, the `/getpublicaudiostream` request gets redirected: `https://*.net/index.php/apps/files/`

**Comment by libasys** [comment]
@szepeviktor thanks for your bug report!
If you share a file you have a link like owncloud/index.php/s/dassjlöjöjlö
Where do you have this sharing link?

Thanks

**Comment by szepeviktor** [comment]
https://qupdate.net/index.php/s/cuPRZnudx4sC2rm

**Comment by libasys** [comment]
No login required with your test file!

**Comment by szepeviktor** [comment]
It is solved in 8.1.1.

Thank you.
